-- AlterTable
ALTER TABLE `employee` MODIFY `company_id` INTEGER NOT NULL DEFAULT 1,
    MODIFY `cost_code` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `date_hired` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `department_id` INTEGER NOT NULL DEFAULT 1,
    MODIFY `employee_no` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `first_name` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `last_name` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `modified_by_id` INTEGER NULL DEFAULT 1;
